---
layout: post
author: pzc
title: Go的defer实现
tags: [Go]
date: 2022-07-03 15:32 +0800
toc:  true
---

## defer作用

defer在函数ret前或者触发panic后会执行，类似于异常处理，但是机制不太一样。g中维护了一个链表_defer（通过deferproc或者deferprocStack创建），在函数返回前可能会调用deferreturn来调用此函数中的defer。如果发生了panic，则会遍历g中的_defer链表，除非defer顶层函数中调用了recover，否则最终会终止程序。
{: .message }

## panic后recover实现

    func main() {
      test()
      fmt.Println("a")
    }
    func test(){
      defer func () {
        panic("a")
      }()
      fmt.Println("test")
    }

![图1](![](https://raw.githubusercontent.com/1053226965/blog/main/imagesSnipaste_2022-07-03_17-41-01.png))